version: "3.5"
services:
  arangodb:
    image: arangodb:latest
    restart: always
    ports:
      - 50001:8529
    environment:
      ARANGO_ROOT_PASSWORD: letmein
    volumes:
      - C:/stg/arangodbstorage:/var/lib/arangodb3
    networks:
      # Networks to join (Services on the same network can communicate with each other using their name)
      - stg
    #command: arangod --server.authentication=false

  backend:
    # Configuration for building the docker image for the service
    build:
      context: ./back # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "50002:50002" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    environment:
      GO_ENV: ${GO_ENV}
      DATABASE_URI_DEV: "http://arangodb:8529"
      DATABASE_URI_PROD: "http://arangodb:8529"
    depends_on:
      - arangodb
    networks:
      # Networks to join (Services on the same network can communicate with each other using their name)
      - stg
    #healthcheck:
    #   test: ["CMD", "curl", "-f", "http://arangodb:8529"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5


  frontend:
    # Configuration for building the docker image for the service
    build:
      context: ./front # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "50003:80" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    networks:
      # Networks to join (Services on the same network can communicate with each other using their name)
      - stg

networks:
  stg:
