version: "3.5"
services:
  backend:
    # Configuration for building the docker image for the service
    build:
      context: ./back # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    environment:
      GO_ENV: ${GO_ENV}
    #depends_on:
    #  - arangodb
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - stg

  frontend:
    # Configuration for building the docker image for the service
    build:
      context: ./front # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - stg
    command: >
      ${ANG_START}

  arangodb:
    image: arangodb:latest
    restart: always
    ports:
      - 8529:8529
    environment:
      ARANGO_ROOT_PASSWORD: letmein
    volumes:
      - ~/stg/arangodb:/var/lib/arangodb3
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - stg

networks:
  stg:
