name: smacktalkgaming
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  dio: ^5.0.3
  deep_pick: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  easy_localization: ^3.0.1
  go_router: ^6.2.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.5
  jwt_decoder: ^2.0.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
