
###

GET http://localhost:50001/_api/database HTTP/1.1
Authorization: Basic root:letmein


###
POST http://127.0.0.1:50002/api/v1/login HTTP/1.1
content-type: application/json

{
    
    "Email": "mitch@gmail.com",
    "Password": "letmein" 
}

###
POST https://smacktalkgaming.com/api/v1/login HTTP/1.1
content-type: application/json

{
    
    "Email": "mitch@gmail.com",
    "Password": "letmein" 
}


