http://localhost:3001/login

###
POST http://localhost:3001/api/v1/login HTTP/1.1
content-type: application/json

{
    "Email": "mitch@gmail.com",
    "Password": "letmein"
}

###
POST http://localhost:4000/api/v1/login HTTP/1.1
content-type: application/json

{
    "Email": "mitch@gmail.com",
    "Password": "letmein"
}

