
###

###
POST http://127.0.0.1:50002/api/v1/users/login HTTP/1.1
content-type: application/json

{
    "Email": "mitch@gmail.com",
    "Password": "letmein"
}

###
POST http://127.0.0.1:50002/api/v1/login HTTP/1.1
content-type: application/json

{
    
    "Email": "mitch@gmail.com",
    "Password": "letmein" 
}


